### PR TITLE
Disable colors if `NO_COLOR` env variable is set

### PR DESCRIPTION
**Pull request by kangasta**

### CODE REVIEW

**Comment by aakso** [comment]
Perhaps rename then flag to NO_COLOURS for consistency with the flag? Of course we could have both spellings.

**Comment by kangasta** [comment]
Many other CLI apps use [NO_COLOR](https://no-color.org/) so for compatibility it would be better even though it looks a bit odd that we use US spelling for env variable but not in options.

**Comment by kangasta** [comment]
But true, we might as well check for both spellings to be both consistent and compatible

**Review by ka-myl — APPROVED** [review]
LGTM.

**Pull request merged**
